### ISSUE TITLE
id and state missing from Billing Agreement after creation.

### ISSUE THREAD

**Issue by diegopamio** [paypal/PayPal-node-SDK#123]
This is really odd, I cannot retrieve the billing agreement id or state after calling creation of the billing agreement... any clue?

I'm using the sandbox.

**Comment by diegopamio** [comment]
I've checked the internals of the sdk, and it looks like the issue is on the API itself, as it doesn't return the ID as it promises on the documentation.

**Comment by fuwaneko** [comment]
I second this. How do I use API if I don't have agreement ID?

**Comment by jaypatel512** [comment]
This is a known inconsistency as compared to payment APIs. However, the agreement will be active when it gets executed after getting the user consent. Once the execute is called, the agreement Id will be returned with the rest of the object.

**Comment by fuwaneko** [comment]
@jaypatel512 I need to save additional data in DB with agreement, so I have to use dirty workarounds because I don't get unique ID from PayPal. If an object is created, API *must* return it's unique ID. Also, execute **does not return** full agreement object, it misses plan.id for example (and in documentation it's shown in example that it returns *only* ID). For now I use agreement token as unique ID to save partial data on create and then append real ID on execute, but that's very dirty. Instead of saying "known inconsistency" just fix it or at least update documentation. REST API is currently very badly implemented, there are no recurring payments notifications, crazy inconsistencies in documentation/actual API, different parts of API work differently, etc. I would use Braintree, but it has no methods to create plans programmatically.

**Comment by ppmtscory** [comment]
@diegopamio can you help me to understand this use case a little better?  Why would you need to check the status of an Agreement prior to sending it off to be approved and subsequently executed?  There is no agreement ID until one is executed as that's when it's generated.  Am I missing something or misunderstanding your request?

**Comment by ppmtscory** [comment]
Closing due to inactivity.  Everything is functioning as intended according to my testing.  There are plans in the works to add verbiage to dev portal to explain that, even though all objects are listed, there are many that are shared, so there may be some are present in one place but not another.  To your issue specifically, only the Plan details are present in the Execute Agreement response - not the Plan ID itself.  The Plan ID doesn't persist through after Agreement creation, just the Plan details.

Feel free to reopen or file a new issue with the previously requested details of your specific use case regarding the Agreement ID prior to approval and execution.

**Comment by gastonelhordoy** [comment]
Hey @ppmtscory, I know this is an old issue, but I just stumbled into the same problem. Based on the [documentation for creating a Billing Agreement](https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_create_response) via the REST API, an ID should be returned.
How can we get this ID?

Thanks in advance for your help!

**Comment by ppmtscory** [comment]
@gastonelhordoy the Plan ID (if that's what you're referring to) is returned in the Create response when the payment method is PayPal.  It doesn't propagate all the way through the Execute; only the Plan details themselves.  Therefore, it won't be present in the Execute response or the Create response when the payment method is credit card (because it's automatically executed).

**Comment by gastonelhordoy** [comment]
Hi @ppmtscory, thanks for replying, but I was referring to the Identifier of the agreement (not the plan). In the documentation I linked, you can see that after creating an Agreement (not yet executed) and ID should be returned in the response but according to my tests it is not.

**Comment by ppmtscory** [comment]
Ah, ok, my apologies.  For that, please see my response from Feb 11th...

Can you help me to understand this use case a little better? Why would you need to check the status of an Agreement prior to sending it off to be approved and subsequently executed? _There is no agreement ID until one is executed as that's when it's generated_.

**Comment by gastonelhordoy** [comment]
I see, I get the reasoning, but this behaviour is not consistent with Payments API.  A payment Id is returned when it is created, even though it has not be executed. 

Furthermore, documentation should be fixed if this is gonna be added, because the response from the create method clearly states that the ID is returned.

**Comment by ppmtscory** [comment]
Thank you for the feedback, @gastonelhordoy, I will chat with our documentation teams on the best way to explain this on the developer site.

**Comment by lawrencemok** [comment]
I still don't understand, the id is in the json response (approval_url) anyway in \\links\[n]\href (e.g. https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-0JP008296V451950C) 

Why don't you just include the id directly in \\id ? It would be much more useful than having it hidden in the links.

**Comment by gastonelhordoy** [comment]
Hey @lawrencemok, that is just the token, it's not the ID itself.

So @ppmtscory, there are no plans to be consistent with the Payment API and return the ID even if Agreement has not been executed?
If you don't mind I ask, what makes these two APIs different? I mean, a newly created Payment has an ID, why a newly create Agreement can have it?

Thanks for your help once again.

**Comment by ppmtscory** [comment]
@gastonelhordoy I'm not aware of any plans to return the ID in the create response for PP payment method agreements.  This would be up to the Product owners to decide, which is why I was asking for use cases where this would be beneficial or use cases where you'd need the BA ID prior to the Execute response.  I'm not privy to any of the original discussions where it may have been decided to do things the way we are, in regards to returning a Pay ID but not a BA ID in a create response.  with that being said, if you provide your use cases to justify the feature, I'll gladly pass those along to the Product team to see about getting this with a future enhancement.

**Comment by gastonelhordoy** [comment]
Well... I know you are not gonna like this answer... but I guess the most simple answer to that would be **"the same use case for having a Payment ID returned by the create method in the Payment API"** :).

**Comment by ppmtscory** [comment]
HA... how did I know that was going to be your answer... ;)

Please open a new issue, tag me in it, and I'll mark it accordingly to track the feature request with our product teams.

**Comment by gastonelhordoy** [comment]
😄 
Done, #215. Thanks a lot for your help!

**Comment by iandeboisblanc** [comment]
Hey. Just wanted to flag that regardless of the product decision, the response does not match [the docs](https://developer.paypal.com/docs/api/payments.billing-agreements/v1/#billing-agreements_create). It might make sense to improve the docs to avoid all kinds of confusion (especially since many people may try to follow the example from payments, which is different).
